### ISSUE TITLE
le README.md du serveur est insuffisant

### ISSUE THREAD

**Issue by evaletolab** [karibou-ch/karibou-quad#10]
Après avoir démarrer le serveur et le client je n'ai pas de donnée. Il faut mentionner comment préparer l'env (dans une section prerequisite)

**Comment by jcavat** [comment]
Je l'ai décrit dans le README principal, à la fin : https://github.com/karibou-ch/karibou-quad

**Comment by evaletolab** [comment]
ok, c'est mieux de le placer dans le readme du server alors :+1:
