### ISSUE TITLE
geler les fonctionnalités pour finaliser le projet (meeting jeudi/18)

### ISSUE THREAD

**Issue by evaletolab** [karibou-ch/karibou-quad#16]
- [x] avoir à l'esprit la priorité des features en fonction du besoin de qualité du consommateur (commandes, boutique, user et produit)
- [x] implémenter les api pour produire les plot à partir des json en input
- [x] le readme principal doit décrire les différentes production du projet (utiliser les liens pour les readme en annexes)
- [x] le readme server+angular doit aussi décrire comment loader les données si on a déjà un mongodb 3.4 local
- [x] florent devrait pouvoir tester le projet sur sa machine en suivant le server/readme.md

**Comment by jcavat** [comment]
Ok, à savoir que la dernière fois j'ai précisé que je faisais mes requêtes avec MongoDB car les primitives d'extractions sont bien plus intéressantes. Je ne me base plus du tout sur le json et refaire marche arrière me prendrait trop de temps.

**Comment by evaletolab** [comment]
Pas de soucis, je souhaite juste une isolation de ces appelles
