### ISSUE TITLE
customer.id in conflict with floatApprox

### ISSUE THREAD

**Issue by jcavat** [karibou-ch/karibou-quad#17]
Certains enregistrements proposent le champ `customer.id.floatApprox` pour stocker l'id du client.

Exemple pour le client F**C: 
```    
"customer": {
      "id": {
        "floatApprox": 1279482934194675
      },
      "pseudo": "F**C",
      "created": "2014-12-13T10:50:39.913Z",
      "likes": []
    },
```

```   
 "customer": {
      "id": 1279482934194675,
      "pseudo": "F**C",
      "created": "2014-12-13T10:50:39.913Z",
      "likes": []
    },
```

**Comment by evaletolab** [comment]
le floatApprox n'existe pas dans mon export! je sais pas d'ou il vient :smile: 
J'en ai profité pour updaté les data  avec le field `price` qui est maintenant `estimatedprice` et le default issue qui est maintenant `issue_missing_product`. Je crois que c'est tout?

**Comment by jcavat** [comment]
Heu, j'ai pas compris. L'extrait que j'ai donné provient de ton export : 

https://github.com/karibou-ch/karibou-quad/blob/a771a27d6c71c5e770bf505f06a82df84eb379e6/tests/data/orders.json

**Comment by evaletolab** [comment]
oui, j'avais bien compris, c'est pas grâve tout est ok maintenant ?

**Comment by jcavat** [comment]
Je ne travaille pas encore sur tes commits. Je suis en train de régler d'autres problèmes mais j'avais résolu en faisant un update au démarrage de docker. Je fais également un update pour les dates pour qu'elle soit en ISODate au lieu de string.
