### ISSUE TITLE
help, problème des scripts avec python3

### ISSUE THREAD

**Issue by evaletolab** [karibou-ch/karibou-quad#19]
Après l'update de mon ubuntu, j'ai remarqué que les scripts ne fonctionnent pas avec la v3 de python. Aurais-tu qq instants à passer sur les scripts pour les rendre à nouveau utilisables? 

D'avance 1000 merci!
Olivier

**Comment by jcavat** [comment]
Salut, ce commit devrait t'aider à résoudre le problème : e14a121199
* changement de path dans les scripts
* README.md dans dossier script qui ajoute deux nouvelles dépendances à installer

**Comment by jcavat** [comment]
ps: il s'agissait de scripts python3. Si le problème persiste, donne-moi le détail sur les erreurs que tu rencontres.
