### ISSUE TITLE
une solution simple est parfois la meilleure (exemple HN)

### ISSUE THREAD

**Issue by evaletolab** [karibou-ch/karibou-quad#2]
C'est juste une note pour rappeler qu'une solution peut être ramenée à qq chose de simple. Exemple avec le rank de hackernews (reddit). Ce qui compte c'est de pouvoir utiliser/évoluer le travail sans avoir besoin de changer nos ressources:
* [HN.YC](http://news.ycombinator.com) rank algor [(p - 1) / (t + 2)^1.5](https://news.ycombinator.com/item?id=231209)
![HN](http://ucarecdn.com/259ee283-7547-4134-b327-b2f8986b6caf/HN.png)

**Comment by jcavat** [comment]
Oui, je suis tombé dessus. J'ai également vu une variante. Je pensais faire une page sur le wiki avec un résumé de mes recherches. Ca te convient ?
