### ISSUE TITLE
Misunderstood status vs issues

### ISSUE THREAD

**Issue by jcavat** [karibou-ch/karibou-quad#3]
Comment interpréter ces cas:
1. parfois, un status est 'fulfilled' alors qu'il y a une issue importante,
2. souvent, un status est 'failure' alors qu'il n'y a aucune issue.

Faut-il considérer les deux cas comme un problème ?

**Comment by evaletolab** [comment]
1. lors d'un fulfilled + issue c'est très **grave**. ça veut dire qu'on a eu l'info de qualité **après** avoir validé et livré le produit. 
2. avec un failure il y a tjrs une issue (par défaut c'est missing_product )!! tu peux me dire à quelle ligne tu as cet exemple?

**Comment by evaletolab** [comment]
j'ai l'impression que tu n'as pas fait de `git pull origin master`

**Comment by jcavat** [comment]
Sur la dernière version:

ligne 77535:
```json      
{
        "title": "Epinard",
        "sku": 1000168,
        "vendor": "sandrine-guy-producteurs",
        "image": "",
        "price": 5,
        "finalprice": 5,
        "qty": 1,
        "category": "Fruits & légumes",
        "status": "failure"
},
```
ligne 95982:
```json    
      {
        "title": "Navet jaune goldana",
        "sku": 1000236,
        "vendor": "sandrine-guy-producteurs",
        "image": "",
        "price": 3.25,
        "finalprice": 3.25,
        "qty": 1,
        "category": "Fruits & légumes",
        "status": "failure"
      },
```
Il y en a d'autres je pense.

**Comment by jcavat** [comment]
Par contre je comprends mieux. Je peux interpréter dans mon code: failure -> missing_product

**Comment by evaletolab** [comment]
Ha, je vois la fonction d'update ne gère pas les multiples modifications dans un document! Je corrige ça , merci

**Comment by jcavat** [comment]
J'ai un autre cas étrange à la ligne ~104764:
```
      {
        "title": "Asperge verte du jardin",
        "sku": 1000193,
        "vendor": "sandrine-guy-producteurs",
        "image": "",
        "price": 16.5,
        "finalprice": 16.5,
        "qty": 2,
        "category": "Fruits & légumes",
        "status": "failure",
        "issue": "issue_wrong_product_quality"
      },
```
Il a un double status: annulé par le vendeur et de mauvaise qualité. Je pensais que failure impliquait missing_product ?

**Comment by evaletolab** [comment]
non, si le problème de qualité est détecté avant la livraison, on annule le produit avec cette qualification. 
La qualification d'un failure peut être, dans l'ordre : `0) issue_no_issue (un failure volontaire), 1) issue_missing_product, 2) issue_wrong_quality`

Si il y a un failure mais aucun issue, alors c'est missing_product par défaut.

**Comment by jcavat** [comment]
Dans mon cas, je le compte quand même comme ```issue_wrong_product_quality```, c'est juste ? Par contre, je n'ai jamais de ```issue_wrong_quality```, mais j'ai des ```issue_wrong_product_quality```. C'est la même chose ?

**Comment by evaletolab** [comment]
oui c'est tjrs `issue_wrong_product_quality`, c'est une erreur dans mon msg.
tu as la liste dans le README.md ,

  * `"issue_no_issue"` **== pas de problème/0** , 
  * `"issue_missing_product"` **== problématique/1**, 
  * `"issue_wrong_product_quality"` et `"items.status===failure"` **== très problématique/2**,
  * `"issue_wrong_product_quality"` et `"items.status===fulfilled"` **== létal/4**,
