### ISSUE TITLE
Implementation of a mapping function

### ISSUE THREAD

**Issue by jcavat** [karibou-ch/karibou-quad#6]
* [x] import JSON file and map data with a first prototype
* [x] prepare MongoDB mock with Docker
* [x] use javascript/typescript for the mapping function with MongoDB Container

**Comment by evaletolab** [comment]
Il faut que la fonction de mapping ainsi que l'opération `aggregate mongo` soit bien documenté

**Comment by jcavat** [comment]
Pour l'instant j'utilise le serveur et les requêtes MongoDB pour faire de l'exploration de données. J'expérimente. Les requêtes changent constamment. Il me reste l'équivalent de 6 jours de travail environ. Il faudra fixer les priorités lors de la séance de ce jeudi.

**Comment by evaletolab** [comment]
Malheureusment je suis pas dispo ce jeudi. C'est pour ça que j'ai créer le milestone. Ce qui est important c'est d'avoir un process complet, même s'il n'est pas parfait. Ce que tu as fait est déjà super top.

**Comment by jcavat** [comment]
Oui, ma priorité est plutôt faire parler les données de manière visuel et de choisir les bons critères. La manière d'extraire l'info sera à peaufiner par la suite si le temps le permet.
