### ISSUE TITLE
Note à propos du scoring basé sur les orders vs items

### ISSUE THREAD

**Issue by evaletolab** [karibou-ch/karibou-quad#8]
Après ta présentation, je me suis demandé pourquoi il y avait un score basé sur l'article et un autre basé sur la commande (item vs transaction). Et aujourd'hui il me paraît évidant que le score basé sur la commande est utile pour l'utilisateur et se décline sur la boutique, et le score basé sur un article est utile pour le produit. Je souhaite savoir comment tu vois la chose?

**Comment by jcavat** [comment]
Je faisais simplement une statistique entre le nombre de problèmes relatif à l'ensemble des commandes et le nombre de problèmes relatif l'ensemble des articles achetés. Un panier peut avoir des issues sur plusieurs articles: une issue avec un vendeur A et une autre issue avec un vendeur B.

**Comment by evaletolab** [comment]
oui, j'avais bien compris, mais je voulais voir avec toi les entités que tu allais caractériser ?

**Comment by jcavat** [comment]
En fait il est préférable de compter le problème par item plutôt que par panier/transaction. Il arrive que certaines transactions comportent plusieurs erreurs.

**Comment by evaletolab** [comment]
oui, mais c'est bien de garder la qualité d'une commande (`ce que tu appelles panier/transaction === order`). Une commande avec plusieurs erreurs a une moins bonne note.

**Comment by jcavat** [comment]
Pour l'instant le système de score est le même. Par contre, je calcule maintenant trois score pour une boutique:
* un score relatif à l'ensemble des produits vendurs
* un score relatif aux transactions
* un score relatif aux nombres de clients impactés

Ce qui offre des classement différent. Il serait intéressant de réfléchir à un score global calculé sur ces trois critères.

**Comment by evaletolab** [comment]
Excellent, btw, `transaction == order` :-) Me réjouis de voir qq chose de concret sur mon poste
