### ISSUE TITLE
Unrecognized pipeline stage name: '$addFields'

### ISSUE THREAD

**Issue by evaletolab** [karibou-ch/karibou-quad#9]
problème  avec `$addFields is introduced in Mongo 3.4 version`. Il faut mentionner la dépendance a mongodb 3.4

**Comment by evaletolab** [comment]
Par contre si c'est embarqué dans ton docker, il faudrait mentionner dans le `readme` (comme prerequisite) comment démarrer le docker.

**Comment by jcavat** [comment]
Je vais ajouter la dépendance dans le readme mais par contre c'est décrit dans le readme comment démarrer docker.

**Comment by jcavat** [comment]
De manière générale la documentation sera plus précises vers la fin du projet.
